language: objective-c
osx_image: xcode10.2
xcode_workspace: AdvancedProd.xcworkspace
xcode_scheme: AdvancedProd
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
- gem install cocoapods
- pod repo update
- pod install